# Generated by Django 4.0.4 on 2022-05-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
    ]
