# Generated by Django 4.0.4 on 2022-05-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_score_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='player_name',
            new_name='player',
        ),
    ]
